### ISSUE TITLE
makeIndex: cannot open file

### ISSUE THREAD

**Issue by robinweide** [robinweide/tagmeppr#8]
I got e-mailed this issue:

> I have preliminary mapping data, but is having trouble running the tagMeppr code. I was able to successfully install the packages and run at R version 4.0.3. But, I am stuck at makeIndex section. While creating tagMepprIndex I am getting this error:
>  “cannot open file '../premadeReferences/BSgenome.Hsapiens.UCSC.hg19_PiggyBac_tagMeppRindex.fa.gz’”
> 
> Do you have sometime so show me way forward? I must say that the entire package at gib hub is well documented, but being a novice in R I might be making some trivial mistake.

**Comment by robinweide** [comment]
Hi,

Could you please add the code you used? 

I'm thinking that you directly copied this code from the vignette:

```{r}
reference_hg19_PB = makeIndex(indexPath = '../premadeReferences/',
                         bsgenome = BSgenome.Hsapiens.UCSC.hg19,
                         ITR = 'PiggyBac',
                         targetInsertionSite = 'TTAA', verbose = T)
```

Can you confirm that there is a folder called premadeReferences at the right place? Try this:

```{r}
dir.exists('../premadeReferences/')
```

**Comment by PankajChaturvedi81** [comment]
Yes, I copied the code from the vignette assuming that the imported library ("BSgenome.Hsapiens.UCSC.hg19") would have a premadeReferences folder. 
dir.exists('../premadeReferences/') shows that there is no such folder.

**Comment by robinweide** [comment]
I see. If you are in your preferred working directory (you can test this with `getwd()`), you can easily make the other directory with `dir.create("premadeReferences")` as a subdirectory of the one you are in now.

**Comment by PankajChaturvedi81** [comment]
First, I loaded the libraries on R ver 4.0.0:
        library(tagMeppr)
	library("BSgenome.Hsapiens.UCSC.hg19")			
	library("BSgenome.Mmusculus.UCSC.mm10")

Then, I created and set the working directory to '../premadeReferences' and ran the next code on vignette. However, i am getting bwa warning.

> reference_hg19_PB = makeIndex(indexPath = '../premadeReferences/',
+ bsgenome = BSgenome.Hsapiens.UCSC.hg19,
+ ITR = 'PiggyBac',
+ targetInsertionSite = 'TTAA', verbose = T)
Loading references
Writing reference
BWA index (this happens in the background and could take hours)
/bin/sh: index: command not found
Scanning insertion-sites
Warning message:
In system("which bwa", intern = T) :
  running command 'which bwa' had status 1

**Comment by robinweide** [comment]
I assume that you have BWA installed.

**Comment by PankajChaturvedi81** [comment]
Thanks,
I was able to map insertions in a mouse ES cell clone of our interest using the code. Will it be possible to continue this thread or a new thread of discussion on these two issues:
1. using a different p value as a cut-off?
2. using T2T genome assembly for aligning human genome reads? The "BSgenome.Hsapiens.NCBI.T2T.CHM13v2.0" version needs R "4.2", but tagmeppr is not availble for this R version 4.2.

**Comment by robinweide** [comment]
Great to hear. Yes, please make new issues for those two questions.
